meta_product_name: "D치 o Lance!"
meta_title: "D치 o Lance"
meta_description: "D치 o Lance traz um novo jeito de fazer suas compras em listas. Pra comprar bem e vender bem, D치 o Lance!"
meta_image: "og-image.jpg"
